# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5-stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v12.4.0/node-v12.4.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.4.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
            npm install yarn -g

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - run:
          name: "Install Buffalo"
          command: |
            wget https://github.com/gobuffalo/buffalo/releases/download/v0.14.6/buffalo_0.14.6_linux_amd64.tar.gz
            tar -xvzf buffalo_0.14.6_linux_amd64.tar.gz
            buffalo build
      - run: ./bin/go_react
